name: lambda pull request

on:
  push:
    branches:
      - main
    paths:
      - environments/dev/*.tf
      - .github/workflows/*.yml
      - modules/**
jobs:
  deployTerrafom:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: environments/dev
    environment:
      name: DEV
    permissions:
      id-token: write      
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::444198540026:role/Github_Terraform_int_role
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.REGION }}
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with: 
          soft_fail: true
          concise-output: true
      # Initialise terraform
      - name: Init
        run: |
          echo "Present directory: $(pwd)"
          terraform init
      - name: Format
        run: |
          echo "Format terraform"
          terraform fmt -recursive
      - name: Validate 
        run: |
          echo "Validate terraform"
          terraform validate
      - name: Plan 
        env: 
          ENVIRONMENT_TYPE: ${{ vars.ENVIRONMENT_TYPE }}
        run: |
          echo "Terraform plan"
          terraform plan -var-file "$ENVIRONMENT_TYPE.tfvars" -out=tfplan      
      - name: Apply 
        env: 
          ENVIRONMENT_TYPE: ${{ vars.ENVIRONMENT_TYPE }}
        run: |
          echo "Terraform apply"
          terraform apply -auto-approve tfplan
