name: lambda pull request

on:
  push:
    branches:
      - main
    paths:
      - environments/dev/*.tf
      - .github/workflows/*.yml
      - modules/**
jobs:
  deployTerrafom:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: environments/${{ vars.ENVIRONMENT_TYPE }}
    environment:
      name: DEV
    permissions:
      id-token: write      
      contents: read
    steps:
      # Checkout repository to runners workspace
      - name: Checkout code
        uses: actions/checkout@v4      
      # Action for Github 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ASSUME_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.REGION }}
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      # Scan config for security 
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with: 
          soft_fail: true
      # Initialise terraform
      - name: Init
        run: |
          echo "Present directory: $(pwd)"
          terraform init
      # Format the tf files 
      - name: Format
        run: |
          echo "Format terraform"
          terraform fmt -recursive
      # Validate the syntax of tf files 
      - name: Validate 
        run: |
          echo "Validate terraform"
          terraform validate
      # Plan gives preview of resources to be created
      - name: Plan 
        env: 
          ENVIRONMENT_TYPE: ${{ vars.ENVIRONMENT_TYPE }}
        run: |
          echo "Terraform plan"
          terraform plan -var-file "$ENVIRONMENT_TYPE.tfvars" -out=tfplan 
      # Shows the output of the plan or state
      - name: Show plan 
        env: 
          ENVIRONMENT_TYPE: ${{ vars.ENVIRONMENT_TYPE }}
        run: |
          echo "Terraform show"
          terraform show   
      # Apply creates the resources   
      - name: Apply 
        env: 
          ENVIRONMENT_TYPE: ${{ vars.ENVIRONMENT_TYPE }}
        run: |
          echo "Terraform apply"
          terraform apply -auto-approve tfplan
